version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile # Указывает на папку с Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - API_URL=http://backend:3000
      - DOMAIN=http://frontend:8080


volumes:
  postgres_data: {}